pull_request_rules:
  - name: Automatic merge ⬇️ on self-approval ✔
    conditions:
      - author=niklasstoffers
      - "#approved-reviews-by>=1"
      - check-success=build
      - "-label=noautomerge"
    actions:
      merge:
        method: merge
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "approved-reviews-by=[niklasstoffers]"
      - check-success=build
      - "-label=noautomerge"
    actions:
      merge:
        method: merge
  - name: Automatic cleanup 🗑️ after merge
    conditions:
      - merged
      - "-label=nocleanup"
    actions:
      delete_head_branch: