pull_request_rules:
  - name: Automatic merge ⬇️ on self-approval ✔
    conditions:
      - author=niklasstoffers
      - "#approved-reviews-by>=1"
      - check-success=build
      - check-success=test
      - base=main
    actions:
      merge:
        method: merge
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "approved-reviews-by=[niklasstoffers]"
      - check-success=build
      - check-success=test
      - base=main
    actions:
      merge:
        method: merge