gitlab_host: https://gitlab.com/
access_token: abc
webhook_token: abc
trusted_hosts_only: true
ssl:
  enable: false
  key_file: /path/to/keyfile
  cert_file: /path/to/certfile
approval:
  keyword: lgtm
  ignore_case: true
  strict_match: true
  only_for_members: null
  message: Merge request has been approved.