gitlab:
  host: https://gitlab.com/
trusted_hosts_only: false
environment: PRODUCTION
ssl:
  enable: false
commands:
  approval:
    keyword: lgtm
    ignore_case: true
    strict_match: true
    only_for_members: null
    message: Merge request has been approved.
  disapproval:
    keyword: lbtm
    ignore_case: true
    strict_match: true
    only_for_members: null
    message: Merge request has been disapproved.
  merge:
    keyword: '@LGTM please merge'
    ignore_case: true
    strict_match: true
    only_for_members: null
    message: Merge request will be merged when pipeline succeeds.
uvicorn:
  reload: false
  host: "0.0.0.0"
  port: 8000
logging:
  enable: true
  level: INFO
  handlers:
    console:
      enable: true