gitlab:
  host: https://gitlab.com/
trusted_hosts_only: false
ssl:
  enable: false
commands:
  approval:
    keyword: lgtm
    ignore_case: true
    strict_match: true
    only_for_members: null
    message: Merge request has been approved.
uvicorn:
  reload: false
  host: "0.0.0.0"
  port: 8000
logging:
  enable: true
  level: INFO
  handlers:
    console:
      enable: true