version: '3.8'
services:
  gitlab-auto-approve:
    container_name: gitlab-auto-approve
    image: gitlab-auto-approve
    build: .
    ports:
      - '${APP_PORT}:80'
    environment:
      - USE_SSL=${USE_SSL}
      - SSL_KEYFILE=${SSL_KEYFILE}
      - SSL_CERTFILE=${SSL_CERTFILE}