version: '3.8'
services:
  gitlab-auto-approve:
    container_name: gitlab-auto-approve
    image: gitlab-auto-approve
    build: .
    ports:
      - '${APP_PORT}:80'
    environment:
      - GITLAB_HOST=${GITLAB_HOST}
      - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
      - GITLAB_WEBHOOK_TOKEN=${GITLAB_WEBHOOK_TOKEN}
      - TRUSTED_HOSTS_ONLY=${TRUSTED_HOSTS_ONLY}
      - USE_SSL=${USE_SSL}
      - SSL_KEYFILE=${SSL_KEYFILE}
      - SSL_CERTFILE=${SSL_CERTFILE}
      - APPROVAL_IGNORE_CASE=${APPROVAL_IGNORE_CASE}
      - APPROVAL_STRICT_MATCH=${APPROVAL_STRICT_MATCH}
      - APPROVAL_ONLY_FOR_MEMBERS=${APPROVAL_ONLY_FOR_MEMBERS}
      - APPROVAL_MESSAGE=${APPROVAL_MESSAGE}