version: '3.8'
services:
  gitlab-auto-approve:
    container_name: gitlab-auto-approve
    image: gitlab-auto-approve
    build: 
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    volumes:
      - ./src:/app/
    ports:
      - '${APP_PORT}:80'
    environment:
      - GITLAB__ACCESS_TOKEN=${GITLAB__ACCESS_TOKEN}
      - GITLAB__WEBHOOK_TOKEN=${GITLAB__WEBHOOK_TOKEN}