gitlab:
  host: https://gitlab.com/
  access_token: abc
  webhook_token: abc
trusted_hosts_only: false
environment: DEVELOPMENT
ssl:
  enable: false
  key_file:
  cert_file:
commands:
  approval:
    keyword: lgtm
    ignore_case: true
    strict_match: true
    only_for_members: null
    message: Merge request has been approved.
  disapproval:
    keyword: lbtm
    ignore_case: true
    strict_match: true
    only_for_members: null
    message: Merge request has been disapproved.
uvicorn:
  reload: false
  host: "0.0.0.0"
  port: 8000
logging:
  enable: true
  level: DEBUG
  handlers:
    console:
      enable: true
    file:
      enable: false
      logfile: