version: 1
disable_existing_loggers: False
formatters:
  startup:
    (): uvicorn.logging.DefaultFormatter
    fmt: "%(levelprefix)s [%(name)s] %(asctime)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  startup_stream:
    class: logging.StreamHandler
    stream: ext://sys.stdout
  startup_file:
    class: logging.FileHandler
    filename: startup.log
root:
  level: DEBUG
loggers:
  asyncio:
    level: INFO
  $startup:
    level: INFO
    handlers: [startup_stream, startup_file]