name: BUILD

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: niklasstoffers/gitlab-auto-approve
        tags: |
          type=sha
    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: type=docker,dest=/tmp/image.tar
    - name: Save artifacts
      id: save-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.meta.outputs.labels }}:${{ steps.meta.outputs.tags }}
        path: /tmp/image.tar
        if-no-files-found: error