name: BUILD

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: type=docker,dest=/tmp/image.tar
    - name: Save artifacts
      id: save-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gitlab-auto-approve--${{ GITHUB_SHA }}
        path: /tmp/image.tar
        if-no-files-found: error