name: BUILD

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: gitlab-auto-approve:latest
        outputs: type=docker,dest=/tmp/image.tar
    - name: Save artifacts
      id: save-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.head_ref }}.${{ github.sha }}
        path: /tmp/image.tar
        if-no-files-found: error