name: PUBLISH

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Wait for test
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'test'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 5
    - name: Wait for lint
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'lint'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 5
    - name: Download build artifacts
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: build.yml
        workflow_conclusion: success
        name: ${{ github.head_ref }}.${{ github.sha }}
        path: /tmp/
        if_no_artifact_found: fail
    - name: Publish
      run: |
        docker load --input /tmp/image.tar
        docker tag gitlab-auto-approve:latest niklasstoffers/gitlab-auto-approve:latest
        docker push niklasstoffers/gitlab-auto-approve:latest
