name: TAG

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    uses: ./.github/workflows/test.yml
  lint:
    uses: ./.github/workflows/test.yml
  tag:
    name: tag
    runs-on: ubuntu-latest
    needs: [build, test, lint]
    steps:
    - name: Download build artifacts
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: build.yml
        workflow_conclusion: success
        name: ${{ github.head_ref }}.${{ github.sha }}
        path: /tmp/
        if_no_artifact_found: fail
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Get version
      id: get-version
      run: echo ::set-output name=VERSION::${GITHUB_REF#ref/tags/}
    - name: Tag and push image
      run: |
        docker load --input /tmp/image.tar
        docker tag gitlab-auto-approve:latest niklasstoffers/gitlab-auto-approve:${{ steps.get-version.outputs.VERSION }}
        docker push niklasstoffers/gitlab-auto-approve:${{ steps.get-version.outputs.VERSION }}