name: TEST

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Wait for build
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'build'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 5
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Download build artifacts
      uses: actions/download-artifacts@v4
      with:
        name: ${{ github.head_ref }}.${{ github.sha }}
        path: /tmp/image.tar
    - name: Run tests
      run: |
        docker load --input /tmp/image.tar
        ./ci_run_tests.sh
