name: TEST

on:
  workflow_run:
    workflows: ["BUILD"]
    branches: ['**']
    types:
      - completed

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Download build artifacts
      uses: actions/download-artifacts@v4
      with:
        name: ${{ github.head_ref }}.${{ github.sha }}
        path: /tmp/image.tar
    - name: Run tests
      run: |
        docker load --input /tmp/image.tar
        ./ci_run_tests.sh
